my_ria_app/config/routes.rb
MyRiaApp::Application.routes.draw do

  scope :api do
    get "/screencasts(.:format)" => "screencasts#index"
    get "/screencasts/:id(.:format)" => "screencasts#show"
  end

  get "games/videos"

  namespace :api do
    resources :shares
  end
  get '/dashboard' => 'home#dashboard'
  devise_scope :user do
    get '/api/current_user' => 'users/sessions#show_current_user', as: 'show_current_user'
    post '/api/check/is_user' => 'users/users#is_user', as: 'is_user'
     end
  get "raffle/index"

  get "home/index"

  get "raffle/index"
  get 'games', to: 'games#index'
  get 'games/who_eats', to: 'games#who_eats'
  get 'games/habitats', to: 'games#habitats'
  get 'games/memory', to: 'games#memory'

  devise_for :users
  root :to => 'home#index'

end

my_ria_app/app/models/screencast.rb
class Screencast < ActiveRecord::Base
  attr_accessible :duration, :link, :published_at, :source, :summary, :title, :video_url
  #validates_presence_of :title, :summary, :duration, :link, :published_at, :source, :video_url
  #validates_uniqueness_of :video_url
end

my_ria_app/app/models/share.rb
class Share < ActiveRecord::Base
  attr_accessible :created_at, :from_user_id, :to_email, :to_user_id, :url
  belongs_to :from, foreign_key: 'from_user_id', class_name: 'User'
  belongs_to :to, foreign_key: 'to_user_id', class_name: 'User'
end

my_ria_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :shares, foreign_key: 'from_user_id'
  end

my_ria_app/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index

  end

  def who_eats

  end

  def videos
  end

  def habitats

  end

  def memory

  end
end

my_ria_app/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def dashboard

  end

  def choose_layout
     user_signed_in? ? "angular" : "application"
  end

  def videos

  end
end

my_ria_app/app/controllers/screencasts_controller.rb
class ScreencastsController < ApplicationController

  def index
    render json: Screencast.all
  end

  # GET /screencasts/:id
  # GET /screencasts/:id.json
  def show
    render json: Screencast.find(params[:id])
  end
end

my_ria_app/app/controllers/shares_controller.rb
class SharesController < ApplicationController
end

my_ria_app/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
   respond_to :json
   def show_current_user
     reject_if_not_authorized_request!
     render status: 200,
              json: {
         success: true,
     info: "Current user",
         user: current_user
     }
     end

   def failure
     render status: 401,
               json: {
         success: false,
     info: "Unauthorized"
     }
     end

   private

   def reject_if_not_authorized_request!
     warden.authenticate!(
         scope: resource_name,
     recall: "#{controller_path}#failure")
     end
   end

my_ria_app/app/controllers/users/users_controllers.rb
class Users::UsersController < Devise::SessionsController
   respond_to :json

   def is_user
     reject_if_not_authorized_request!
     render status: 200,
              json: {
         success: !User.find_by_name(params[:name]).blank?
     }

     end
   private

   def reject_if_not_authorized_request!
     warden.authenticate!(
          scope: resource_name,
      recall: "#{controller_path}#failure")
      end
    end

my_ria_app/app/helpers/screencasts_helper.rb
module ScreencastsHelper
end

my_ria_app/app/helpers/shares_helper.rb
module SharesHelper
end

my_ria_app/app/views/games/habitats.html.erb
<script type="text/javascript">
	function savanna()
	{
		var xmlhttp = new XMLHttpRequest();
		xmlhttp.onreadystatechange=function()
		{
			if (xmlhttp.readyState==4 && xmlhttp.status==200)
				{
					var JSONObject = JSON.parse(xmlhttp.responseText);
					document.getElementById("name").innerHTML = "<span style='font-weight:bold'>Name: </span>" + JSONObject.savannaName;
					document.getElementById("category").innerHTML = "<span style='font-weight:bold'>Habitate Type: </span>" +  JSONObject.savannaType;
					document.getElementById("bio").innerHTML = "<span style='font-weight:bold'>About Habitate: </span>" +  JSONObject.aboutSavanna;
				}
		}
		xmlhttp.open("GET","../assets/habitats.json",true);
		xmlhttp.send();
	}
	
	function jungle()
	{
		var xmlhttp = new XMLHttpRequest();
		xmlhttp.onreadystatechange=function()
		{
			if (xmlhttp.readyState==4 && xmlhttp.status==200)
				{
					var JSONObject = JSON.parse(xmlhttp.responseText);
					document.getElementById("name").innerHTML = "<span style='font-weight:bold'>Name: </span>" + JSONObject.jungleName;
					document.getElementById("category").innerHTML = "<span style='font-weight:bold'>Category: </span>" + JSONObject.jungleType;
					document.getElementById("bio").innerHTML = "<span style='font-weight:bold'>Biography: </span>" + JSONObject.aboutJungle;
				}
		}
		xmlhttp.open("GET","../assets/habitats.json",true);
		xmlhttp.send();
	}
	
	function desert()
	{
		var xmlhttp = new XMLHttpRequest();
		xmlhttp.onreadystatechange=function()
		{
			if (xmlhttp.readyState==4 && xmlhttp.status==200)
				{
					var JSONObject = JSON.parse(xmlhttp.responseText);
					document.getElementById("name").innerHTML = "<span style='font-weight:bold'>Name: </span>" + JSONObject.desertName;
					document.getElementById("category").innerHTML = "<span style='font-weight:bold'>Category: </span>" + JSONObject.desertType;
					document.getElementById("bio").innerHTML = "<span style='font-weight:bold'>Biography: </span>" + JSONObject.aboutDesert;
				}
		}
		xmlhttp.open("GET","../assets/habitats.json",true);
		xmlhttp.send();
	}
</script>

<div>
	<div class="row">
		<p id="habitatsHeader">Click on a Picture to Learn about the Habitat</p>
	</div>
</div>

<div class="row">
	<div id="habitatsImages">
	<img class="span4 habitatsPictures" src="../assets/ajax_images/savanna.jpg" alt="Savanna Image" title="Savanna" width="300" height="200" onclick="savanna()" />
	
	
	<img class="span4 habitatsPictures" src="../assets/ajax_images/jungle.jpg" alt="Jungle Image" title="Jungle" width="300" height="200" onclick="jungle()" />
	
	
	<img class="span4 habitatsPictures" src="../assets/ajax_images/desert.jpg" alt="Desert Image" title="Desert" width="300" height="200" onclick="desert()" />
	</div>
</div>


<div id="textArea">
	<p class="habitatText" id="name"></p>
	<p class="habitatText" id="category"></p>	
	<p class="habitatText" id="bio"></p>
</div>


my_ria_app/app/views/games/index.html.erb
<%= stylesheet_link_tag "style_countries" %>
<%= javascript_include_tag "countries" %>


<section id="preguntas">
  <article class="preg">
    Japan
  </article>

  <article class="preg">
    United states
  </article>

  <article class="preg">
    France
  </article>

  <article class="preg">
    United kingdom
  </article>

  <article class="preg">
    China
  </article>

  <article class="preg">
    Germany
  </article>



  <div id="respuestas">
    <%= image_tag "level1/china.png", :class => "respuesta" , :alt => "china"%>
    <%= image_tag "level1/germany.png", :class => "respuesta" , :alt => "germany"%>
    <%= image_tag "level1/england.png", :class => "respuesta", :alt => "england" %>
    <%= image_tag "level1/japan.png", :class => "respuesta" , :alt => "japan"%>
    <%= image_tag "level1/usa.png", :class => "respuesta" , :alt => "usa"%>
    <%= image_tag "level1/france.png", :class => "respuesta" , :alt => "france"%>

  </div>

</section>
<div id="resultados">

</div>

my_ria_app/app/views/games/memory.html.erb
<h1>hey dave!!!!!!!!</h1>

my_ria_app/app/views/games/quiz.html.erb
<div ng-app="QuizApp">



<p>Im ta quiz</p>
</div>

my_ria_app/app/views/games/videos.html.erb
<div ng-app="AngularCasts">
  <div ng-controller="ScreencastsCtrl">

    <div id="screencast-list-container" >
      <ul>
        <li ng-repeat="screencast in screencasts"
            ng-click="showScreencast(screencast)">
          <h3>{{screencast.title}} <small>({{screencast.duration}})</small></h3>
        </li>
      </ul>
    </div>

    <div id="screencast-view-container" ng-show="selectedScreencast">
      <h2>{{selectedScreencast.title}}</h2>
      <p>{{selectedScreencast.summary}}</p>
      <div flow-player="" id="player"></div>
      <p>
        Published at {{selectedScreencast.published_at | date: 'mediumDate'}}
        - <a ng-href="{{selectedScreencast.link}}">{{selectedScreencast.link}}</a>
      </p>
    </div>

  </div>



</div>

my_ria_app/app/views/games/who_eats.html.erb
<%= stylesheet_link_tag "main" %>
<%= stylesheet_link_tag "rps" %>
<script type="text/javascript">
    var dndSupported;    // true if drag and drop supported
    var dndEls = new Array();
    var draggingElement;
    var winners = {
        Wildebeest: 'Lion',
        Leafs: 'Giraffe',
        Grass: 'Wildebeest',
        Bananas: 'Monkey',
        Lilies: 'Hippo'
    };

    var hoverBorderStyle = '2px dashed #999';
    var normalBorderStyle = '2px solid white';

    function detectDragAndDrop() {
        if (navigator.appName == 'Microsoft Internet Explorer') {
            var ua = navigator.userAgent;
            var re  = new RegExp("MSIE ([0-9]{1,}[\.0-9]{0,})");
            if (re.exec(ua) != null) {
                var rv = parseFloat( RegExp.$1 );
                if(rv >= 6.0) return true;
            }
            return false;
        }
        if ('draggable' in document.createElement('span')) return true;
        return false;
    }

    // DnD support

    function handleDragStart(e) {
        var rpsType = getRPSType(this);
        draggingElement = this;
        draggingElement.className = 'moving';
        statusMessage('Drag ' + rpsType);
        this.style.opacity = '0.4';
        this.style.border = hoverBorderStyle;
        e.dataTransfer.setDragImage(getRPSImg(this), 120, 120); // set the drag image

    }

    function handleDragEnd(e) {
        this.style.opacity = '1.0';

        // reset the element style
        draggingElement.className = undefined;
        draggingElement = undefined;

        // reset all of the elements
        for(var i = 0; i < dndEls.length; i++) {
            dndEls[i].style.border = normalBorderStyle;
        }
    }

    function handleDragOver(e) {
        if(e.preventDefault) e.preventDefault();
        this.style.border = hoverBorderStyle;

        return false;   // some browsers may need this to prevent default action
    }

    function handleDragEnter(e) {
        if(this !== draggingElement) statusMessage('Hover ' + getRPSType(draggingElement)    + ' over ' + getRPSType(this));
        this.style.border = hoverBorderStyle;
    }

    function handleDragLeave(e) {
        this.style.border = normalBorderStyle;
    }

    function handleDrop(e) {
        if(e.stopPropegation) e.stopPropagation(); // Stops some browsers from redirecting.
        if(e.preventDefault) e.preventDefault();
        if(this.id === draggingElement.id) return;
        else isWinner(this, draggingElement);
    }

    // utility functions *****************************************************************************************
    function isWinner(under, over) {
        var underType = getRPSType(under);
        var overType = getRPSType(over);
        if(overType == winners[underType]) {
            statusMessage(overType + ' eats ' + underType);
            swapRPS(under, over);
        } else {
            statusMessage(overType + ' does not eat ' + underType);
        }
    }

    function getRPSFooter(e) {
        var children = e.childNodes;
        for( var i = 0; i < children.length; i++ ) {
            if( children[i].nodeName.toLowerCase() == 'footer' ) return children[i];
        }
        return undefined;
    }

    function getRPSImg(e) {
        var children = e.childNodes;
        for( var i = 0; i < children.length; i++ ) {
            if( children[i].nodeName.toLowerCase() == 'img' ) return children[i];
        }
        return undefined;
    }

    function getRPSType(e) {
        var footer = getRPSFooter(e);
        if(footer) return footer.innerHTML;
        else return undefined;
    }

    function swapRPS(a, b) {
        var holding = Object();

        holding.img = getRPSImg(a);
        holding.src = holding.img.src;
        holding.footer = getRPSFooter(a);
        holding.type = holding.footer.innerHTML;

        holding.img.src = getRPSImg(b).src;
        holding.footer.innerHTML = getRPSType(b);

        getRPSImg(b).src = holding.src;
        getRPSFooter(b).innerHTML = holding.type;
    }

    // Utility functions

    var elStatus;
    function element(id) { return document.getElementById(id); }

    function statusMessage(s) {
        if(!elStatus) elStatus = element('statusMessage');
        if(!elStatus) return;
        if(s) elStatus.innerHTML = s;
        else elStatus.innerHTML = '&nbsp;';
    }

    // App lifetime support

    function init() {
        if((dndSupported = detectDragAndDrop())) {
            statusMessage('Drag and Drop images to see if you\'re correct');
            dndEls.push(element('rps1'), element('rps2'), element('rps3'), element('rps4'), element('rps5'),  element('rps6'), element('rps7'), element('rps8'), element('rps9'));
            for(var i = 0; i < dndEls.length; i++) {
                dndEls[i].addEventListener('dragstart', handleDragStart, false);
                dndEls[i].addEventListener('dragend', handleDragEnd, false);
                dndEls[i].addEventListener('dragover', handleDragOver, false);
                dndEls[i].addEventListener('dragenter', handleDragEnter, false);
                dndEls[i].addEventListener('dragleave', handleDragLeave, false);
                dndEls[i].addEventListener('drop', handleDrop, false);
            }
        } else {
            statusMessage('This browser does not support Drag and Drop');
        }
    }

    window.onload = function() {
        init();
    }
</script>
<div id="content">

  <h1>
    Herbivore's & Carnivore's - Who Eats What in Africa???
  </h1>

  <p class="message" id="statusMessage" />

  <div id="columns">
    <div class="rps" id="rps1"><%= image_tag "images_who_eats/lion.jpg", :draggable=>"true"%><footer>Lion</Footer></div>
    <div class="rps" id="rps2"><%= image_tag "images_who_eats/wildebeest.jpg", :draggable=>"true"%><footer>Wildebeest</Footer></div>
    <div class="rps" id="rps3"><%= image_tag "images_who_eats/leafs.jpg", :draggable=>"true"%><footer>Leafs</Footer></div>
    <div class="rps" id="rps4"><%= image_tag "images_who_eats/giraffe.jpg", :draggable=>"true"%><footer>Giraffe</Footer></div>
    <div class="rps" id="rps5"><%= image_tag "images_who_eats/grass.jpg", :draggable=>"true"%><footer>Grass</Footer></div>
    <div class="rps" id="rps6"><%= image_tag "images_who_eats/monkey.jpg", :draggable=>"true"%><footer>Monkey</Footer></div>
    <div class="rps" id="rps7"><%= image_tag "images_who_eats/bananas.jpg", :draggable=>"true"%><footer>Bananas</Footer></div>
    <div class="rps" id="rps8"><%= image_tag "images_who_eats/hippo.jpg", :draggable=>"true"%><footer>Hippo</Footer></div>
    <div class="rps" id="rps9"><%= image_tag "images_who_eats/lilies.jpg", :draggable=>"true"%><footer>Lilies</Footer></div>
  </div>

  <p id="clear" /> <!-- provide some space at the bottom -->

</div>
<

my_ria_app/app/views/home/dashboard.html.erb
<div ng-app="myApp">

  <div ng-controller="HomeController">

    <ul>
      <li ng-repeat="article in articles | orderBy:publishedDate:false">
        <div class="article-listing">
          <div class="large-11 small-11 columns">
            <h2>
              <a
              href="{{ article.link }}"
              title="{{ article.title }}">
                {{ article.title }}
              </a>
            </h2>
            <p>
              {{ article.publishedDate | date:'M/d/yy h:mm:ss a' }}
            </p>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div> >

my_ria_app/app/views/layouts/angular.html.erb
<!DOCTYPE html>
 <html lang="en" data-ng-app="myApp">
 <head>
 <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title><%= content_for?(:title) ? yield(:title) : "shareup" %></title>
 <%= csrf_meta_tags %>
 <%= stylesheet_link_tag "application", :media => "all" %>
 </head>
<body>
<header>


</header>
 <div class="container">
 <h1>Text!</h1>
 <div data-ng-view></div>
 </div> <!-- /container -->
 <%= javascript_include_tag "application" %>
 </body>
 </html>

my_ria_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyRiaApp</title>
  <link href="//releases.flowplayer.org/5.4.0/skin/minimalist.css" rel="stylesheet">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <script src="//releases.flowplayer.org/5.4.0/flowplayer.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<header>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Go Wild!</a>
    <ul class="nav">
      <li class="active"><%= link_to "Home", home_index_path %></li>
      <li><%= link_to "News", dashboard_path %></li>
      <li><%= link_to "Games", games_path %></li>
      <li><%= link_to "Videos", games_videos_path %></li>
      <li><%= link_to "Who eats what?", games_who_eats_path %></li>
      <li><%= link_to "Habitats", games_habitats_path %></li>
      <li><%= link_to "Memory", games_memory_path %></li>
      <li><%= link_to "Raffle", raffle_index_path %></li>
      <li><%= link_to "Sign in", new_user_session_path %></li>
    </ul>
  </div>
</div>

</header>


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
<script src="//releases.flowplayer.org/5.4.0/flowplayer.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular-resource.min.js"></script>
<%= yield %>

<%= javascript_include_tag "application" %>
</body>
</html>